var tree = [["[Global Namespace]",,"",
                [["DatabaseException","DatabaseException.html"," < RuntimeException",
                [        ]],["DbClientRequestException","DbClientRequestException.html"," < RuntimeException",
                [        ]],["PermissionsException","PermissionsException.html"," < RuntimeException",
                [        ]]        ]],["MicheleAngioni",,"",
                [["Support","MicheleAngioni\/Support.html","",
                [["Cache","MicheleAngioni\/Support\/Cache.html","",
                [["AbstractCacheRepositoryDecorator","MicheleAngioni\/Support\/Cache\/AbstractCacheRepositoryDecorator.html","",
                [        ]],["AbstractCacheSimpleXMLRepositoryDecorator","MicheleAngioni\/Support\/Cache\/AbstractCacheSimpleXMLRepositoryDecorator.html","",
                [        ]],["CacheInterface","MicheleAngioni\/Support\/Cache\/CacheInterface.html","",
                [        ]],["KeyManager","MicheleAngioni\/Support\/Cache\/KeyManager.html","",
                [        ]],["KeyManagerInterface","MicheleAngioni\/Support\/Cache\/KeyManagerInterface.html","",
                [        ]],["LaravelCache","MicheleAngioni\/Support\/Cache\/LaravelCache.html","",
                [        ]]        ]],["Facades","MicheleAngioni\/Support\/Facades.html","",
                [["Helpers","MicheleAngioni\/Support\/Facades\/Helpers.html"," < Facade",
                [        ]]        ]],["Repos","MicheleAngioni\/Support\/Repos.html","",
                [["AbstractEloquentRepository","MicheleAngioni\/Support\/Repos\/AbstractEloquentRepository.html","",
                [        ]],["AbstractSimpleXMLRepository","MicheleAngioni\/Support\/Repos\/AbstractSimpleXMLRepository.html","",
                [        ]],["RepositoryCacheableQueriesInterface","MicheleAngioni\/Support\/Repos\/RepositoryCacheableQueriesInterface.html","",
                [        ]],["XMLRepositoryInterface","MicheleAngioni\/Support\/Repos\/XMLRepositoryInterface.html","",
                [        ]]        ]],["Semaphores","MicheleAngioni\/Support\/Semaphores.html","",
                [["SemaphoresManager","MicheleAngioni\/Support\/Semaphores\/SemaphoresManager.html","",
                [        ]]        ]],["Helpers","MicheleAngioni\/Support\/Helpers.html","",
                [        ]],["SupportServiceProvider","MicheleAngioni\/Support\/SupportServiceProvider.html"," < ServiceProvider",
                [        ]]        ]]        ]]        ]

