var tree = [["MicheleAngioni",,"",
                [["Support","MicheleAngioni\/Support.html","",
                [["Cache","MicheleAngioni\/Support\/Cache.html","",
                [["AbstractCacheRepositoryDecorator","MicheleAngioni\/Support\/Cache\/AbstractCacheRepositoryDecorator.html","",
                [        ]],["AbstractCacheSimpleXMLRepositoryDecorator","MicheleAngioni\/Support\/Cache\/AbstractCacheSimpleXMLRepositoryDecorator.html","",
                [        ]],["CacheInterface","MicheleAngioni\/Support\/Cache\/CacheInterface.html","",
                [        ]],["KeyManager","MicheleAngioni\/Support\/Cache\/KeyManager.html","",
                [        ]],["KeyManagerInterface","MicheleAngioni\/Support\/Cache\/KeyManagerInterface.html","",
                [        ]],["LaravelCache","MicheleAngioni\/Support\/Cache\/LaravelCache.html","",
                [        ]]        ]],["Exceptions","MicheleAngioni\/Support\/Exceptions.html","",
                [["DatabaseException","MicheleAngioni\/Support\/Exceptions\/DatabaseException.html"," < RuntimeException",
                [        ]],["DbClientRequestException","MicheleAngioni\/Support\/Exceptions\/DbClientRequestException.html"," < RuntimeException",
                [        ]],["PermissionsException","MicheleAngioni\/Support\/Exceptions\/PermissionsException.html"," < RuntimeException",
                [        ]]        ]],["Facades","MicheleAngioni\/Support\/Facades.html","",
                [["Helpers","MicheleAngioni\/Support\/Facades\/Helpers.html"," < Facade",
                [        ]]        ]],["Presenters","MicheleAngioni\/Support\/Presenters.html","",
                [["AbstractPresenter","MicheleAngioni\/Support\/Presenters\/AbstractPresenter.html","",
                [        ]],["PresentableInterface","MicheleAngioni\/Support\/Presenters\/PresentableInterface.html","",
                [        ]],["Presenter","MicheleAngioni\/Support\/Presenters\/Presenter.html","",
                [        ]]        ]],["Repos","MicheleAngioni\/Support\/Repos.html","",
                [["AbstractEloquentRepository","MicheleAngioni\/Support\/Repos\/AbstractEloquentRepository.html","",
                [        ]],["AbstractSimpleXMLRepository","MicheleAngioni\/Support\/Repos\/AbstractSimpleXMLRepository.html","",
                [        ]],["RepositoryCacheableQueriesInterface","MicheleAngioni\/Support\/Repos\/RepositoryCacheableQueriesInterface.html","",
                [        ]],["XMLRepositoryInterface","MicheleAngioni\/Support\/Repos\/XMLRepositoryInterface.html","",
                [        ]]        ]],["Semaphores","MicheleAngioni\/Support\/Semaphores.html","",
                [["SemaphoresManager","MicheleAngioni\/Support\/Semaphores\/SemaphoresManager.html","",
                [        ]]        ]],["CustomValidators","MicheleAngioni\/Support\/CustomValidators.html"," < Validator",
                [        ]],["Helpers","MicheleAngioni\/Support\/Helpers.html","",
                [        ]],["SupportServiceProvider","MicheleAngioni\/Support\/SupportServiceProvider.html"," < ServiceProvider",
                [        ]]        ]]        ]]        ]

